name: snapstudy
description: A flashcard app that creates cards from book pages or slides.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+5
  path_provider: ^2.1.1
  path: ^1.8.3
  permission_handler: ^11.0.1
  google_mlkit_text_recognition: ^0.11.0
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  image_picker: ^1.0.4
  flutter_markdown: ^0.6.18
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  cached_network_image: ^3.3.0
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env 