name: CI/CD Pipeline for SnapStudy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

  - name: Install Tesseract OCR
  run: sudo apt-get update && sudo apt-get install -y tesseract-ocr

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r back/requirements.txt

    - name: Run tests
      run: |
        cd back
        pytest

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./back
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/snapstudy-backend:latest